[package]
name = "greentic-oauth-core"
version.workspace = true
edition = "2024"

[features]
default = []
schemas = ["schemars", "serde_json"]

[dependencies]
base64 = { workspace = true }
rand = { workspace = true }
sha2 = { workspace = true }
jsonwebtoken = "9"
serde = { workspace = true }
schemars = { workspace = true, optional = true }
serde_json = { workspace = true, optional = true }
thiserror = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
uuid = { workspace = true }
